### ISSUE TITLE
get_cof_per_tariff method creation?

### ISSUE THREAD

**Issue by XaviTorello** [gisce/enerdata#49]
Can be interesting to extend enerdata to integrate get_cof_per_tariff(tariff_name) method?

To reach the cof (A,B,C,D) for a specific tariff name.

If it, I will make the related PR.

**Comment by ecarreras** [comment]
Maybe you can simple assign the coeficient as a Class attribute

**Comment by XaviTorello** [comment]
Yes, of course!
